//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UR3
{
    [Serializable]
    public class UR3_MoveitJointsMsg : Message
    {
        public const string k_RosMessageName = "ur3_moveit/UR3_MoveitJoints";
        public override string RosMessageName => k_RosMessageName;

        public double[] joints;
        public Geometry.PoseMsg pick_pose_blueball_1;
        public Geometry.PoseMsg pick_pose_blueball_2;
        public Geometry.PoseMsg pick_pose_redball_1;
        public Geometry.PoseMsg pick_pose_redball_2;
        public Geometry.PoseMsg Place_basket_1;
        public Geometry.PoseMsg Place_basket_2;

        public UR3_MoveitJointsMsg()
        {
            this.joints = new double[6];
            this.pick_pose_blueball_1 = new Geometry.PoseMsg();
            this.pick_pose_blueball_2 = new Geometry.PoseMsg();
            this.pick_pose_redball_1 = new Geometry.PoseMsg();
            this.pick_pose_redball_2 = new Geometry.PoseMsg();
            this.Place_basket_1 = new Geometry.PoseMsg();
            this.Place_basket_2 = new Geometry.PoseMsg();
        }

        public UR3_MoveitJointsMsg(double[] joints, Geometry.PoseMsg pick_pose_blueball_1, Geometry.PoseMsg pick_pose_blueball_2, Geometry.PoseMsg pick_pose_redball_1, Geometry.PoseMsg pick_pose_redball_2, Geometry.PoseMsg Place_basket_1, Geometry.PoseMsg Place_basket_2)
        {
            this.joints = joints;
            this.pick_pose_blueball_1 = pick_pose_blueball_1;
            this.pick_pose_blueball_2 = pick_pose_blueball_2;
            this.pick_pose_redball_1 = pick_pose_redball_1;
            this.pick_pose_redball_2 = pick_pose_redball_2;
            this.Place_basket_1 = Place_basket_1;
            this.Place_basket_2 = Place_basket_2;
        }

        public static UR3_MoveitJointsMsg Deserialize(MessageDeserializer deserializer) => new UR3_MoveitJointsMsg(deserializer);

        private UR3_MoveitJointsMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.joints, sizeof(double), 6);
            this.pick_pose_blueball_1 = Geometry.PoseMsg.Deserialize(deserializer);
            this.pick_pose_blueball_2 = Geometry.PoseMsg.Deserialize(deserializer);
            this.pick_pose_redball_1 = Geometry.PoseMsg.Deserialize(deserializer);
            this.pick_pose_redball_2 = Geometry.PoseMsg.Deserialize(deserializer);
            this.Place_basket_1 = Geometry.PoseMsg.Deserialize(deserializer);
            this.Place_basket_2 = Geometry.PoseMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.joints);
            serializer.Write(this.pick_pose_blueball_1);
            serializer.Write(this.pick_pose_blueball_2);
            serializer.Write(this.pick_pose_redball_1);
            serializer.Write(this.pick_pose_redball_2);
            serializer.Write(this.Place_basket_1);
            serializer.Write(this.Place_basket_2);
        }

        public override string ToString()
        {
            return "UR3_MoveitJointsMsg: " +
            "\njoints: " + System.String.Join(", ", joints.ToList()) +
            "\npick_pose_blueball_1: " + pick_pose_blueball_1.ToString() +
            "\npick_pose_blueball_2: " + pick_pose_blueball_2.ToString() +
            "\npick_pose_redball_1: " + pick_pose_redball_1.ToString() +
            "\npick_pose_redball_2: " + pick_pose_redball_2.ToString() +
            "\nPlace_basket_1: " + Place_basket_1.ToString() +
            "\nPlace_basket_2: " + Place_basket_2.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
