//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UR3
{
    [Serializable]
    public class MoverServiceRequest : Message
    {
        public const string k_RosMessageName = "ur3_moveit/MoverService";
        public override string RosMessageName => k_RosMessageName;

        public UR3_MoveitJointsMsg joints_input;
        public Geometry.PoseMsg pick_pose_blueball_1;
        public Geometry.PoseMsg pick_pose_blueball_2;
        public Geometry.PoseMsg pick_pose_redball_1;
        public Geometry.PoseMsg pick_pose_redball_2;
        public Geometry.PoseMsg Place_basket_1;
        public Geometry.PoseMsg Place_basket_2;

        public MoverServiceRequest()
        {
            this.joints_input = new UR3_MoveitJointsMsg();
            this.pick_pose_blueball_1 = new Geometry.PoseMsg();
            this.pick_pose_blueball_2 = new Geometry.PoseMsg();
            this.pick_pose_redball_1 = new Geometry.PoseMsg();
            this.pick_pose_redball_2 = new Geometry.PoseMsg();
            this.Place_basket_1 = new Geometry.PoseMsg();
            this.Place_basket_2 = new Geometry.PoseMsg();
        }

        public MoverServiceRequest(UR3_MoveitJointsMsg joints_input, Geometry.PoseMsg pick_pose_blueball_1, Geometry.PoseMsg pick_pose_blueball_2, Geometry.PoseMsg pick_pose_redball_1, Geometry.PoseMsg pick_pose_redball_2, Geometry.PoseMsg Place_basket_1, Geometry.PoseMsg Place_basket_2)
        {
            this.joints_input = joints_input;
            this.pick_pose_blueball_1 = pick_pose_blueball_1;
            this.pick_pose_blueball_2 = pick_pose_blueball_2;
            this.pick_pose_redball_1 = pick_pose_redball_1;
            this.pick_pose_redball_2 = pick_pose_redball_2;
            this.Place_basket_1 = Place_basket_1;
            this.Place_basket_2 = Place_basket_2;
        }

        public static MoverServiceRequest Deserialize(MessageDeserializer deserializer) => new MoverServiceRequest(deserializer);

        private MoverServiceRequest(MessageDeserializer deserializer)
        {
            this.joints_input = UR3_MoveitJointsMsg.Deserialize(deserializer);
            this.pick_pose_blueball_1 = Geometry.PoseMsg.Deserialize(deserializer);
            this.pick_pose_blueball_2 = Geometry.PoseMsg.Deserialize(deserializer);
            this.pick_pose_redball_1 = Geometry.PoseMsg.Deserialize(deserializer);
            this.pick_pose_redball_2 = Geometry.PoseMsg.Deserialize(deserializer);
            this.Place_basket_1 = Geometry.PoseMsg.Deserialize(deserializer);
            this.Place_basket_2 = Geometry.PoseMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.joints_input);
            serializer.Write(this.pick_pose_blueball_1);
            serializer.Write(this.pick_pose_blueball_2);
            serializer.Write(this.pick_pose_redball_1);
            serializer.Write(this.pick_pose_redball_2);
            serializer.Write(this.Place_basket_1);
            serializer.Write(this.Place_basket_2);
        }

        public override string ToString()
        {
            return "MoverServiceRequest: " +
            "\njoints_input: " + joints_input.ToString() +
            "\npick_pose_blueball_1: " + pick_pose_blueball_1.ToString() +
            "\npick_pose_blueball_2: " + pick_pose_blueball_2.ToString() +
            "\npick_pose_redball_1: " + pick_pose_redball_1.ToString() +
            "\npick_pose_redball_2: " + pick_pose_redball_2.ToString() +
            "\nPlace_basket_1: " + Place_basket_1.ToString() +
            "\nPlace_basket_2: " + Place_basket_2.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
